### ISSUE TITLE
External stylesheets aren't being reloaded

### ISSUE THREAD

**Issue by elliottsj** [ahuth/emcee#24]
Hey again,

External stylesheets are working now (https://github.com/ahuth/emcee/issues/23), but aren't being reloaded upon making changes to the stylesheet.

For example:

``` html
<!-- app/assets/components/signin-register/signin-register.html -->
<polymer-element name="signin-register" noscript>
  <template>
    <link href="signin-register.css.scss" rel="stylesheet">
    <main-layout>
      <span class="title">Sign in / Register</span>
      <paper-button class="button" label="Sign in"></paper-button>
      <paper-button class="button" label="Register"></paper-button>
    </main-layout>
  </template>
</polymer-element>
```

``` scss
// app/assets/components/signin-register/signin-register.css.scss
@import "mixins";

.button {
  background: $primary-color-dark;
  color: white;
}
```

Results in the following CSS:

``` css
/* line 3, .../app/assets/components/signin-register/signin-register.css.scss */
.button {
  background: #455a64;
  color: white;
}
```

But when I make changes to the stylesheet...

``` scss
// app/assets/components/signin-register/signin-register.css.scss
@import "mixins";

.button {
  background: black;
  color: white;
}
```

The CSS remains the same as before:

``` css
/* line 3, .../app/assets/components/signin-register/signin-register.css.scss */
.button {
  background: #455a64;
  color: white;
}
```

I've found that [railtie.rb#L26](https://github.com/ahuth/emcee/blob/fe9c81bda68c10ff0b427209e870c6ea7beb300e/lib/emcee/railtie.rb#L26) is only executed when the HTML changes (not when just the stylesheet changes), but beyond that, I'm not sure how to solve this issue.

Thanks!
